---

- name: Local - Configure the timezone
  template: src=timezone.j2 dest=/etc/timezone

- name: Local - More Configure the timezone
  file: src=/usr/share/zoneinfo/{{local_timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Local - Set default system language pack
  locale_gen: name={{local_locale}} state=present

- name: Local - Set default system language pack - export LANG and LC_ALL
  shell: export LC_ALL={{local_locale}} && export LANG={{local_locale}} && export LANGUAGE={{local_locale}}

- name: Local - Ensure LANG is set system-wide in /etc/profile.d/ for PostgreSQL 2/2
  shell: echo 'export LANG={{local_locale}}' > /etc/profile.d/lizmap_box_set_lang

- name: Install some packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - apt-transport-https
    - nano
    - vim
    - htop
    - sudo
    - git
    - acl # for become
