name: "Cypress ðŸŽ³"
on:
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]
    branches:
      - master
      - release_3_*
  schedule:
    # Run every monday at 3:00
    - cron:  '0 3 * * 1'
  workflow_dispatch:

jobs:
  cypress:
    # The first condition is triggered when we set the new label
    # The second one when we update the PR with new commits without changing labels
    # The third one when it's a cron job
    # The fourth one is for the manual button
    if: |
      github.event.label.name == 'run cypress' ||
      contains(github.event.pull_request.labels.*.name, 'run cypress') ||
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch'
    name: "Cypress"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        qgis-server-version: [3.16, 3.22]
    env:
      LZMQGSRVVERSION: ${{ matrix.qgis-server-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Install Lizmap as a QGIS Server plugin
        run: cd tests && ./add_server_plugins.sh

      - name: Pull docker images
        run: cd tests && ./run-docker pull

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build and start docker images
        run: cd tests && ./run-docker up --build -d

      - name: Wait docker images ready and install Lizmap
        run: cd tests && sleep 30 && ./lizmap-ctl install

      - name: Load SQL data
        run: cd tests/qgis-projects/tests && ./load_sql.sh

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          working-directory: tests/end2end
          spec: cypress/integration/*-ghaction.js
          wait-on: http://localhost:8130

      - name: Save screenshots as artifacts if a test fails to ease debug
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: |
            tests/end2end/cypress/screenshots
            tests/end2end/cypress/downloads

      - name: Display Lizmap errors.log and fail if not empty
        run: |
          if [ -s "lizmap/var/log/errors.log" ]; then
            echo "errors.log not empty!";
            cat lizmap/var/log/errors.log;
            exit -1;
          fi
#  debug:
#    name: "Debug"
#    runs-on: ubuntu-latest
#    steps:
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: |
#          echo "$GITHUB_CONTEXT"
