name: "Cypress ðŸŽ³"
on:
  schedule:
    # Run every monday at 3:00
    - cron:  '0 3 * * 1'
  workflow_dispatch:
jobs:
  cypress:
    name: "Cypress"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Lizmap as a QGIS Server plugin
        run: cd tests && ./add_server_plugins.sh

      - name: Pull docker images
        run: cd tests && ./run-docker pull

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build and start docker images
        run: cd tests && ./run-docker up --build -d

      - name: Wait docker images ready and install Lizmap
        run: cd tests && sleep 30 && ./lizmap-ctl install

      - name: Load SQL data
        run: cd tests/qgis-projects/tests && ./load_sql.sh

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          working-directory: tests/js
          wait-on: http://localhost:8130
          # Some tests might pass in local but not in CI, we don't add them below (e.g. popup_spec.js)
          spec: |
            cypress/integration/form_edition_all_field_type_spec.js
            cypress/integration/form_edition_reverse_geom_spec.js
            cypress/integration/form_edition_spec.js
            cypress/integration/selectionTool_spec.js
            cypress/integration/test_import_kml_spec.js

      - name: Save screenshots as artifacts if a test fails to ease debug
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/js/cypress/screenshots

      - name: Display Lizmap errors.log and fail if not empty
        run: |
          if [ -s "lizmap/var/log/errors.log" ]; then
            echo "errors.log not empty!";
            cat lizmap/var/log/errors.log;
            exit -1;
          fi
