name: "ðŸš® Close feedback issues"
on:
  schedule:
  - cron: "0 4 * * 2,5"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v8.0.0
      with:
        repo-token: ${{ secrets.BOT_HUB_TOKEN }}
        days-before-stale: 30
        days-before-close: 7
        operations-per-run: 10
        stale-issue-message: |
          This issue is missing some feedbacks.  ðŸ‘»
          Please have a look to the discussion, thanks. ðŸ¦Ž
        stale-issue-label: 'stale'
        only-labels: 'feedback'
