name: "ðŸ˜ PHPStan"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release_3_*
  pull_request:
    branches:
      - master
      - release_3_*

defaults:
  run:
    working-directory: ./lizmap

jobs:
  phpstan:
    name: "Analyze"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: '8.1'
          - php-version: '8.2'
          - php-version: '8.3'
          - php-version: '8.4'
    steps:
      - uses: actions/checkout@v4

      - name: Get composer cache directory
        id: get-composer-cache-dir
        run: echo "composer_cache_dir=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        # About the PHP version, do not forget to change in PHP Unit as well
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpstan:1.11.11
          ini-values: error_reporting=22527

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.composer_cache_dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHPStan version
        run: |
          phpstan -V
          echo "PHPSTAN_VERSION=$(phpstan -V)" >> $GITHUB_ENV

      - name: Run PHPStan
        id: test-phpstan
        run: phpstan analyse -c ../phpstan-ci.neon

      - name: Notify in case of failure but not on a PR
        uses: peter-evans/commit-comment@v3
        if: failure() && github.event_name != 'pull_request'
        with:
          body: |
            The latest run of **PHPStan** has **failed**, maybe it's due to a newer version released recently ðŸ˜£
            Current version used on CI :

            > ${{ env.PHPSTAN_VERSION }}

            https://github.com/phpstan/phpstan/releases

            Have a look to **your** current version of PHPStan like :

            âž¡ `docker exec CONTAINER_test_php tests/units/vendor/phpstan/phpstan/phpstan -V`

            And update if needed :

            âž¡ `./lizmap-ctl composer-update`
