name: "ðŸ˜ PHPStan"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release_3_*
  pull_request:
    branches:
      - master
      - release_3_*

defaults:
  run:
    working-directory: ./lizmap

jobs:
  phpstan:
    name: "Analyze"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get composer cache directory
        id: get-composer-cache-dir
        run: echo "composer_cache_dir=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phpstan

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.composer_cache_dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHPStan version
        run: |
          phpstan -V
          echo "PHPSTAN_VERSION=$(phpstan -V)" >> $GITHUB_ENV

      - name: Run PHPStan
        id: test-phpstan
        run: phpstan analyse -c ../phpstan.neon

      - name: Notify in case of failure
        uses: peter-evans/commit-comment@v2
        if: failure()
        with:
          body: |
            The latest run of **PHPStan** has **failed**, maybe it's due to a newer version released recently ðŸ˜£
            Current version used on CI :

            > ${{ env.PHPSTAN_VERSION }}

            Have a look to **your** current version of PHPStan like :

            âž¡ `docker exec CONTAINER_test_php tests/units/vendor/phpstan/phpstan/phpstan -V`

            And update if needed :

            âž¡ `./limap-ctl composer-update`
