name: "ðŸŒ€ Close stale issues"
on:
  schedule:
  - cron: "0 4 * * 1,3"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9.1.0
      with:
#        repo-token: ${{ secrets.BOT_HUB_TOKEN }}
        days-before-stale: 180
        days-before-close: 15
        operations-per-run: 10
        stale-issue-message: |
          Hiya!
          This issue has gone quiet.  ðŸ‘»
          We get a few questions in the bug tracker, we are currently slowly closing issues.
          If we missed this issue or if you want to keep it open, please reply here.
          As a friendly reminder: the best way to see this issue, or any other, fixed is to open a Pull Request.
          Thanks for being a part of the Lizmap community! ðŸ¦Ž
        stale-issue-label: 'stale'
        exempt-issue-labels: 'bug,enhancement,doc-needed,new feature,Feature request'
